version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres2
    environment:
      POSTGRES_USER: leydi
      POSTGRES_PASSWORD: root
      POSTGRES_DB: servicio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
